volumes:
  taxi_rides_ny_postgres_data:
    driver: local

services:
  warehouse:
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: taxi_rides_ny
    ports:
      - "5432:5432"
    volumes:
      - taxi_rides_ny_postgres_data:/var/lib/postgresql
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8085:80"
    depends_on:
      warehouse:
        condition: service_started